rodetransportes/config/routes.rb
Rails.application.routes.draw do
  resources :estoques
  resources :frota
  resources :terceirizados
  resources :colaboradors
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rodetransportes/app/models/colaborador.rb
class Colaborador < ApplicationRecord
end

rodetransportes/app/controllers/colaboradors_controller.rb
class ColaboradorsController < ApplicationController
  before_action :set_colaborador, only: [:show, :edit, :update, :destroy]

  # GET /colaboradors
  # GET /colaboradors.json
  def index
    @colaboradors = Colaborador.all
  end

  # GET /colaboradors/1
  # GET /colaboradors/1.json
  def show
  end

  # GET /colaboradors/new
  def new
    @colaborador = Colaborador.new
  end

  # GET /colaboradors/1/edit
  def edit
  end

  # POST /colaboradors
  # POST /colaboradors.json
  def create
    @colaborador = Colaborador.new(colaborador_params)

    respond_to do |format|
      if @colaborador.save
        format.html { redirect_to @colaborador, notice: 'Colaborador was successfully created.' }
        format.json { render :show, status: :created, location: @colaborador }
      else
        format.html { render :new }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colaboradors/1
  # PATCH/PUT /colaboradors/1.json
  def update
    respond_to do |format|
      if @colaborador.update(colaborador_params)
        format.html { redirect_to @colaborador, notice: 'Colaborador was successfully updated.' }
        format.json { render :show, status: :ok, location: @colaborador }
      else
        format.html { render :edit }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaboradors/1
  # DELETE /colaboradors/1.json
  def destroy
    @colaborador.destroy
    respond_to do |format|
      format.html { redirect_to colaboradors_url, notice: 'Colaborador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colaborador
      @colaborador = Colaborador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colaborador_params
      params.require(:colaborador).permit(:nome, :cpf, :rg, :celular, :whatsapp, :email)
    end
end

rodetransportes/app/helpers/colaboradors_helper.rb
module ColaboradorsHelper
end

rodetransportes/app/views/colaboradors/_form.html.erb
<%= form_with(model: colaborador, local: true) do |form| %>
  <% if colaborador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(colaborador.errors.count, "error") %> prohibited this colaborador from being saved:</h2>

      <ul>
      <% colaborador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :rg %>
    <%= form.text_field :rg %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.text_field :celular %>
  </div>

  <div class="field">
    <%= form.label :whatsapp %>
    <%= form.text_field :whatsapp %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rodetransportes/app/views/colaboradors/edit.html.erb
<h1>Editing Colaborador</h1>

<%= render 'form', colaborador: @colaborador %>

<%= link_to 'Show', @colaborador %> |
<%= link_to 'Back', colaboradors_path %>

rodetransportes/app/views/colaboradors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colaboradors</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Rg</th>
      <th>Celular</th>
      <th>Whatsapp</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colaboradors.each do |colaborador| %>
      <tr>
        <td><%= colaborador.nome %></td>
        <td><%= colaborador.cpf %></td>
        <td><%= colaborador.rg %></td>
        <td><%= colaborador.celular %></td>
        <td><%= colaborador.whatsapp %></td>
        <td><%= colaborador.email %></td>
        <td><%= link_to 'Show', colaborador %></td>
        <td><%= link_to 'Edit', edit_colaborador_path(colaborador) %></td>
        <td><%= link_to 'Destroy', colaborador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Colaborador', new_colaborador_path %>

rodetransportes/app/views/colaboradors/new.html.erb
<h1>New Colaborador</h1>

<%= render 'form', colaborador: @colaborador %>

<%= link_to 'Back', colaboradors_path %>

rodetransportes/app/views/colaboradors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @colaborador.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @colaborador.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @colaborador.rg %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @colaborador.celular %>
</p>

<p>
  <strong>Whatsapp:</strong>
  <%= @colaborador.whatsapp %>
</p>

<p>
  <strong>Email:</strong>
  <%= @colaborador.email %>
</p>

<%= link_to 'Edit', edit_colaborador_path(@colaborador) %> |
<%= link_to 'Back', colaboradors_path %>