rodetransportes/config/routes.rb
Rails.application.routes.draw do
  resources :estoques
  resources :frota
  resources :terceirizados
  resources :colaboradors
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rodetransportes/app/models/terceirizado.rb
class Terceirizado < ApplicationRecord
end

rodetransportes/app/controllers/terceirizados_controller.rb
class TerceirizadosController < ApplicationController
  before_action :set_terceirizado, only: [:show, :edit, :update, :destroy]

  # GET /terceirizados
  # GET /terceirizados.json
  def index
    @terceirizados = Terceirizado.all
  end

  # GET /terceirizados/1
  # GET /terceirizados/1.json
  def show
  end

  # GET /terceirizados/new
  def new
    @terceirizado = Terceirizado.new
  end

  # GET /terceirizados/1/edit
  def edit
  end

  # POST /terceirizados
  # POST /terceirizados.json
  def create
    @terceirizado = Terceirizado.new(terceirizado_params)

    respond_to do |format|
      if @terceirizado.save
        format.html { redirect_to @terceirizado, notice: 'Terceirizado was successfully created.' }
        format.json { render :show, status: :created, location: @terceirizado }
      else
        format.html { render :new }
        format.json { render json: @terceirizado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terceirizados/1
  # PATCH/PUT /terceirizados/1.json
  def update
    respond_to do |format|
      if @terceirizado.update(terceirizado_params)
        format.html { redirect_to @terceirizado, notice: 'Terceirizado was successfully updated.' }
        format.json { render :show, status: :ok, location: @terceirizado }
      else
        format.html { render :edit }
        format.json { render json: @terceirizado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terceirizados/1
  # DELETE /terceirizados/1.json
  def destroy
    @terceirizado.destroy
    respond_to do |format|
      format.html { redirect_to terceirizados_url, notice: 'Terceirizado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_terceirizado
      @terceirizado = Terceirizado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def terceirizado_params
      params.require(:terceirizado).permit(:nome, :cpf, :rg, :celular, :email, :caminhao, :placacaminhao, :renavancaminhao, :cegonha, :placacegonha, :renavancegonha)
    end
end

rodetransportes/app/helpers/terceirizados_helper.rb
module TerceirizadosHelper
end

rodetransportes/app/views/terceirizados/_form.html.erb
<%= form_with(model: terceirizado, local: true) do |form| %>
  <% if terceirizado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(terceirizado.errors.count, "error") %> prohibited this terceirizado from being saved:</h2>

      <ul>
      <% terceirizado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :rg %>
    <%= form.text_field :rg %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.text_field :celular %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :caminhao %>
    <%= form.text_field :caminhao %>
  </div>

  <div class="field">
    <%= form.label :placacaminhao %>
    <%= form.text_field :placacaminhao %>
  </div>

  <div class="field">
    <%= form.label :renavancaminhao %>
    <%= form.text_field :renavancaminhao %>
  </div>

  <div class="field">
    <%= form.label :cegonha %>
    <%= form.text_field :cegonha %>
  </div>

  <div class="field">
    <%= form.label :placacegonha %>
    <%= form.text_field :placacegonha %>
  </div>

  <div class="field">
    <%= form.label :renavancegonha %>
    <%= form.text_field :renavancegonha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rodetransportes/app/views/terceirizados/edit.html.erb
<h1>Editing Terceirizado</h1>

<%= render 'form', terceirizado: @terceirizado %>

<%= link_to 'Show', @terceirizado %> |
<%= link_to 'Back', terceirizados_path %>

rodetransportes/app/views/terceirizados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Terceirizados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Rg</th>
      <th>Celular</th>
      <th>Email</th>
      <th>Caminhao</th>
      <th>Placacaminhao</th>
      <th>Renavancaminhao</th>
      <th>Cegonha</th>
      <th>Placacegonha</th>
      <th>Renavancegonha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @terceirizados.each do |terceirizado| %>
      <tr>
        <td><%= terceirizado.nome %></td>
        <td><%= terceirizado.cpf %></td>
        <td><%= terceirizado.rg %></td>
        <td><%= terceirizado.celular %></td>
        <td><%= terceirizado.email %></td>
        <td><%= terceirizado.caminhao %></td>
        <td><%= terceirizado.placacaminhao %></td>
        <td><%= terceirizado.renavancaminhao %></td>
        <td><%= terceirizado.cegonha %></td>
        <td><%= terceirizado.placacegonha %></td>
        <td><%= terceirizado.renavancegonha %></td>
        <td><%= link_to 'Show', terceirizado %></td>
        <td><%= link_to 'Edit', edit_terceirizado_path(terceirizado) %></td>
        <td><%= link_to 'Destroy', terceirizado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Terceirizado', new_terceirizado_path %>

rodetransportes/app/views/terceirizados/new.html.erb
<h1>New Terceirizado</h1>

<%= render 'form', terceirizado: @terceirizado %>

<%= link_to 'Back', terceirizados_path %>

rodetransportes/app/views/terceirizados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @terceirizado.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @terceirizado.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @terceirizado.rg %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @terceirizado.celular %>
</p>

<p>
  <strong>Email:</strong>
  <%= @terceirizado.email %>
</p>

<p>
  <strong>Caminhao:</strong>
  <%= @terceirizado.caminhao %>
</p>

<p>
  <strong>Placacaminhao:</strong>
  <%= @terceirizado.placacaminhao %>
</p>

<p>
  <strong>Renavancaminhao:</strong>
  <%= @terceirizado.renavancaminhao %>
</p>

<p>
  <strong>Cegonha:</strong>
  <%= @terceirizado.cegonha %>
</p>

<p>
  <strong>Placacegonha:</strong>
  <%= @terceirizado.placacegonha %>
</p>

<p>
  <strong>Renavancegonha:</strong>
  <%= @terceirizado.renavancegonha %>
</p>

<%= link_to 'Edit', edit_terceirizado_path(@terceirizado) %> |
<%= link_to 'Back', terceirizados_path %>