rodetransportes/config/routes.rb
Rails.application.routes.draw do
  resources :estoques
  resources :frota
  resources :terceirizados
  resources :colaboradors
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rodetransportes/app/models/estoque.rb
class Estoque < ApplicationRecord
end

rodetransportes/app/controllers/estoques_controller.rb
class EstoquesController < ApplicationController
  before_action :set_estoque, only: [:show, :edit, :update, :destroy]

  # GET /estoques
  # GET /estoques.json
  def index
    @estoques = Estoque.all
  end

  # GET /estoques/1
  # GET /estoques/1.json
  def show
  end

  # GET /estoques/new
  def new
    @estoque = Estoque.new
  end

  # GET /estoques/1/edit
  def edit
  end

  # POST /estoques
  # POST /estoques.json
  def create
    @estoque = Estoque.new(estoque_params)

    respond_to do |format|
      if @estoque.save
        format.html { redirect_to @estoque, notice: 'Estoque was successfully created.' }
        format.json { render :show, status: :created, location: @estoque }
      else
        format.html { render :new }
        format.json { render json: @estoque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estoques/1
  # PATCH/PUT /estoques/1.json
  def update
    respond_to do |format|
      if @estoque.update(estoque_params)
        format.html { redirect_to @estoque, notice: 'Estoque was successfully updated.' }
        format.json { render :show, status: :ok, location: @estoque }
      else
        format.html { render :edit }
        format.json { render json: @estoque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estoques/1
  # DELETE /estoques/1.json
  def destroy
    @estoque.destroy
    respond_to do |format|
      format.html { redirect_to estoques_url, notice: 'Estoque was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estoque
      @estoque = Estoque.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estoque_params
      params.require(:estoque).permit(:veiculo, :placa, :cor, :ano, :chassi, :chave, :funciona, :banco, :dataentrada, :reboque, :enderecocoleta, :tipoentrada, :datasaida, :local, :situacao, :transportado)
    end
end

rodetransportes/app/helpers/estoques_helper.rb
module EstoquesHelper
end

rodetransportes/app/views/estoques/_form.html.erb
<%= form_with(model: estoque, local: true) do |form| %>
  <% if estoque.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estoque.errors.count, "error") %> prohibited this estoque from being saved:</h2>

      <ul>
      <% estoque.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :veiculo %>
    <%= form.text_field :veiculo %>
  </div>

  <div class="field">
    <%= form.label :placa %>
    <%= form.text_field :placa %>
  </div>

  <div class="field">
    <%= form.label :cor %>
    <%= form.text_field :cor %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.text_field :ano %>
  </div>

  <div class="field">
    <%= form.label :chassi %>
    <%= form.text_field :chassi %>
  </div>

  <div class="field">
    <%= form.label :chave %>
    <%= form.text_field :chave %>
  </div>

  <div class="field">
    <%= form.label :funciona %>
    <%= form.text_field :funciona %>
  </div>

  <div class="field">
    <%= form.label :banco %>
    <%= form.text_field :banco %>
  </div>

  <div class="field">
    <%= form.label :dataentrada %>
    <%= form.text_field :dataentrada %>
  </div>

  <div class="field">
    <%= form.label :reboque %>
    <%= form.text_field :reboque %>
  </div>

  <div class="field">
    <%= form.label :enderecocoleta %>
    <%= form.text_field :enderecocoleta %>
  </div>

  <div class="field">
    <%= form.label :tipoentrada %>
    <%= form.text_field :tipoentrada %>
  </div>

  <div class="field">
    <%= form.label :datasaida %>
    <%= form.text_field :datasaida %>
  </div>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local %>
  </div>

  <div class="field">
    <%= form.label :situacao %>
    <%= form.text_field :situacao %>
  </div>

  <div class="field">
    <%= form.label :transportado %>
    <%= form.text_field :transportado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rodetransportes/app/views/estoques/edit.html.erb
<h1>Editing Estoque</h1>

<%= render 'form', estoque: @estoque %>

<%= link_to 'Show', @estoque %> |
<%= link_to 'Back', estoques_path %>

rodetransportes/app/views/estoques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estoques</h1>

<table>
  <thead>
    <tr>
      <th>Veiculo</th>
      <th>Placa</th>
      <th>Cor</th>
      <th>Ano</th>
      <th>Chassi</th>
      <th>Chave</th>
      <th>Funciona</th>
      <th>Banco</th>
      <th>Dataentrada</th>
      <th>Reboque</th>
      <th>Enderecocoleta</th>
      <th>Tipoentrada</th>
      <th>Datasaida</th>
      <th>Local</th>
      <th>Situacao</th>
      <th>Transportado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estoques.each do |estoque| %>
      <tr>
        <td><%= estoque.veiculo %></td>
        <td><%= estoque.placa %></td>
        <td><%= estoque.cor %></td>
        <td><%= estoque.ano %></td>
        <td><%= estoque.chassi %></td>
        <td><%= estoque.chave %></td>
        <td><%= estoque.funciona %></td>
        <td><%= estoque.banco %></td>
        <td><%= estoque.dataentrada %></td>
        <td><%= estoque.reboque %></td>
        <td><%= estoque.enderecocoleta %></td>
        <td><%= estoque.tipoentrada %></td>
        <td><%= estoque.datasaida %></td>
        <td><%= estoque.local %></td>
        <td><%= estoque.situacao %></td>
        <td><%= estoque.transportado %></td>
        <td><%= link_to 'Show', estoque %></td>
        <td><%= link_to 'Edit', edit_estoque_path(estoque) %></td>
        <td><%= link_to 'Destroy', estoque, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estoque', new_estoque_path %>

rodetransportes/app/views/estoques/new.html.erb
<h1>New Estoque</h1>

<%= render 'form', estoque: @estoque %>

<%= link_to 'Back', estoques_path %>

rodetransportes/app/views/estoques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Veiculo:</strong>
  <%= @estoque.veiculo %>
</p>

<p>
  <strong>Placa:</strong>
  <%= @estoque.placa %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @estoque.cor %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @estoque.ano %>
</p>

<p>
  <strong>Chassi:</strong>
  <%= @estoque.chassi %>
</p>

<p>
  <strong>Chave:</strong>
  <%= @estoque.chave %>
</p>

<p>
  <strong>Funciona:</strong>
  <%= @estoque.funciona %>
</p>

<p>
  <strong>Banco:</strong>
  <%= @estoque.banco %>
</p>

<p>
  <strong>Dataentrada:</strong>
  <%= @estoque.dataentrada %>
</p>

<p>
  <strong>Reboque:</strong>
  <%= @estoque.reboque %>
</p>

<p>
  <strong>Enderecocoleta:</strong>
  <%= @estoque.enderecocoleta %>
</p>

<p>
  <strong>Tipoentrada:</strong>
  <%= @estoque.tipoentrada %>
</p>

<p>
  <strong>Datasaida:</strong>
  <%= @estoque.datasaida %>
</p>

<p>
  <strong>Local:</strong>
  <%= @estoque.local %>
</p>

<p>
  <strong>Situacao:</strong>
  <%= @estoque.situacao %>
</p>

<p>
  <strong>Transportado:</strong>
  <%= @estoque.transportado %>
</p>

<%= link_to 'Edit', edit_estoque_path(@estoque) %> |
<%= link_to 'Back', estoques_path %>